/*
Conferences attended by Xiao-Nan LU in the academic year of 2024
*/

var confName24=[
    "日本数学会2025年度年会",
    "2025早稲田離散数理研究集会",
    "日本OR学会研究部会「最適化の理論とアルゴリズム」第9回研究会",
    "電子情報通信学会 情報理論研究会 (IT)",
    "電子情報通信学会 情報理論研究会 (IT)",
    "スペクトラルグラフ理論および周辺領域 第13回研究集会",
    "NII共同研究「解集合プログラミングの実用化に向けた並列解法に関する研究開発」第3回全体会合",
    "2024年度応用数学合同研究集会",
    "The International Symposium on Information Theory and Its Applications (ISITA) 2024",
    "NII共同研究「解集合プログラミングの実用化に向けた並列解法に関する研究開発」第2回全体会合",
    "研究集会「情報・計算・暗号の融合による新しい数理基盤の創出」",
    "日本応用数理学会 2024年度年会",
    "電子情報通信学会 2024年度ソサイエティ大会",
    "The 26th Japan Conference on Discrete and Computational Geometry, Graphs, and Games (JCDCG^3)",
    "日本数学会 2024年度秋季総合分科会",
    "第８回日本組合せゲーム理論研究集会",
    "RIMS 共同研究「組合せ最適化セミナー」",
    "第7回金沢暗号理論勉強会",
    "NII共同研究「解集合プログラミングの実用化に向けた並列解法に関する研究開発」第1回全体会合",
    "2024年度人工知能学会全国大会",
	"公開講演会「プライバシー保護とデータサイエンス」"
];

var confPlace24=[
    "早稲田大学",
    "早稲田大学",
    "国立情報学研究所・Zoom (オンライン参加)",
    "大阪大学中之島センター",
    "海峡メッセ下関・Zoom (オンライン参加)",
    "早稲田大学・Zoom (オンライン参加)",
    "高松センタービル",
    "龍谷大学 (瀬田キャンパス)",
    "National Taiwan University of Science and Technology, Taipei",
    "名古屋大学",
    "JR博多シティとZoomによるハイブリッド開催 (オンライン参加)",
    "京都大学",
    "日本工業大学",
    "Tokyo University of Science (Kagurazaka Campus)",
    "大阪大学 (豊中キャンパス)",
    "名古屋大学・オンライン",
    "京都大学",
    "石川県政しいのき迎賓館・オンライン (オンライン参加)",
    "松本商工会議所(長野県松本市)",
    "アクトシティ浜松(静岡県浜松市)・オンライン",
    "統計数理研究所・オンライン (オンライン参加)"
];
			
var confData24=[
    "3月18日～21日",
    "3月16日～17日",
    "3月10日",
    "3月5日～6日",
    "1月29日～30日",
    "1月26日～28日",
    "12月23日～24日",
    "12月5日～7日",
    "Nov 10 - 13, 2024",
    "10月28日～29日",
    "9月25日～27日",
    "9月14日～16日",
    "9月10日～13日",
    "Sept 10 - 12, 2024", 
    "9月3日～6日",
    "8月23日～24日",
    "8月6日～8日",
    "7月26日～27日",
    "6月26日～27日",
    "5月28日～31日",
    "5月24日"
];
			
var confURL24=[
    "https://www.mathsoc.jp/activity/meeting/waseda25mar/index.html",
    "https://sites.google.com/view/waseda-dm",
    "https://orsj.org/raota/",
    "https://ken.ieice.org/ken/program/index.php?tgs_regid=8451807f7254aa941b2649ca5a232e06e19e40d93e835088d0426b3970092cba",
    "https://ken.ieice.org/ken/program/index.php?tgs_regid=888ee1cbec09a76efd8dc131b42018cdd5440254183a559e0b306ef581f93632",
    "https://hajimetanaka.org/docs/sgt13/",
    "https://nabesima.github.io/nii2024/#3RD",
    "https://www.mathsoc.jp/section/appliedmath/CAM/2024/index.html",
    "https://isita.ieice.org/2024/",
    "https://nabesima.github.io/nii2024/#2ND",
    "https://joint.imi.kyushu-u.ac.jp/post-14912/",
    "https://jsiam.org/annual2024/",
    "https://www.ieice.org/jpn_r/activities/taikai/society/2024/",
    "https://sites.google.com/view/jcdcg2024",
    "https://www.mathsoc.jp/activity/meeting/osaka24sept/index.html",
    "https://sites.google.com/view/jcgtw/%E7%A0%94%E7%A9%B6%E9%9B%86%E4%BC%9A",
    "https://www.kurims.kyoto-u.ac.jp/coss/coss2024/coss2024.html",
    "https://sites.google.com/view/kanazawacryptgraphy2024/",
    "https://nabesima.github.io/nii2024/",
    "https://www.ai-gakkai.or.jp/jsai2024/",
    "https://www.ism.ac.jp/openhouse/2024/index.html"
];
			
var confRmks24=[
    "“Existentially closed critical Cayley graphs” 3/18",
    "",
    "",
    "",
    "",
    "",
    "",
    "“Cop number and capture time of incidence graphs of combinatorial designs” 12/7",
    "“Improved Quasi-Random Designs with Constant Pool Sizes for Group Testing” 11/12",
    "",
    "",
    "",
    "",
    "“Cop number and capture time on incidence graphs of Steiner 2-designs” 9/11",
    "",
    "",
    "",
    "",
    "",
    "",
    ""
];
